#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: batch/v1
kind: Job
metadata:
  name: couchdb-init
  namespace: nuvolaris
spec:
  backoffLimit: 3
  template:
    metadata:
      name: couchdb-init
      namespace: nuvolaris
    spec:
      serviceAccount: nuvolaris-operator
      restartPolicy: Never      
      containers:
      - name: init-couchdb
        image: "ghcr.io/francescotimperi/nuvolaris-operator:0.3.0-morpheus.23021019"
        imagePullPolicy: "IfNotPresent"
        command: ["./dbinit.sh"]
        env:
        - name: "NUVOLARIS_CONFIG"
          value: |
            {
            "components.couchdb": true,
            "components.invoker": false,
            "components.kafka": false,
            "components.mongodb": false,
            "components.openwhisk": true,
            "components.redis": true,
            "components.s3bucket": false,
            "couchdb.admin.password": "some_passw0rd",
            "couchdb.admin.user": "whisk_admin",
            "couchdb.invoker.password": "s0meP@ass1",
            "couchdb.invoker.user": "invoker_admin",
            "couchdb.host": "couchdb",
            "couchdb.controller.password": "s0meP@ass2",
            "couchdb.controller.user": "controller_admin",
            "couchdb.port": 5984,
            "couchdb.volume-size": 10,
            "kafka.host": "kafka",
            "kafka.volume-size": 10,
            "mongodb.admin.password": "0therPa55",
            "mongodb.admin.user": "admin",
            "mongodb.host": "mongodb",
            "mongodb.volume-size": 10,
            "openwhisk.limits.actions.invokes-concurrent": 250,
            "openwhisk.limits.actions.invokes-perMinute": 999,
            "openwhisk.limits.actions.sequence-maxLength": 50,
            "openwhisk.limits.triggers.fires-perMinute": 999,
            "openwhisk.namespaces.whisk-system": "789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2Bx1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP",
            "openwhisk.namespaces.nuvolaris": "cbd68075-dac2-475e-8c07-d62a30c7e683:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP",                                                                                  
            "s3.id": "AKIAIOSFODNN7EXAMPLE",
            "s3.key": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
            "s3.region": "eu-central-1",
            "s3.volume-size": 10,
            "nuvolaris.storageClass": "standard",
            "nuvolaris.provisioner": "rancher.io/local-path",
            "nuvolaris.apihost": "localhost",
            "nuvolaris.apiport": "3233",
            "nuvolaris.kube": "kind",
            "nuvolaris.protocol": "http",
            "operator.image": "ghcr.io/francescotimperi/nuvolaris-operator",
            "operator.tag": "0.3.0-morpheus.23021019",
            "controller.image": "ghcr.io/nuvolaris/openwhisk-controller",
            "controller.tag": "0.3.0-morpheus.22122609"
            }
