# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "apisix-ingress-controller.fullname" . }}-apisix-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.gateway.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- include "apisix-ingress-controller.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080
    - name: https
      protocol: TCP
      port: {{ .Values.gateway.tls.servicePort }}
      targetPort: {{ .Values.gateway.tls.containerPort }}
  selector:
    {{- include "apisix-ingress-controller.selectorLabels" . | nindent 4 }}
  type: {{ .Values.gateway.type }} # LoadBalancer or NodePort
  {{- if or (eq .Values.gateway.type "LoadBalancer") (eq .Values.gateway.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.gateway.externalTrafficPolicy }}
  {{- end }}
  {{- if eq .Values.gateway.type "LoadBalancer" }}
  {{- if .Values.gateway.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gateway.loadBalancerIP }} # specify load balancer ip by user
  {{- end }}
  {{- if .Values.gateway.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.gateway.loadBalancerSourceRanges }}
  - {{ $cidr }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if gt (len .Values.gateway.externalIPs) 0 }}
  externalIPs:
  {{- range $ip := .Values.gateway.externalIPs }}
  - {{ $ip }}
  {{- end }}
  {{- end }}